name: Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # 每12小时更新一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # 如果你设置了 PAT：token: ${{ secrets.METRICS_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Minamiyama
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai

          # 常用插件（可按需增删）
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: pr, issue, review, push

          # 生成到根目录
          output_action: commit
          committer_branch: main
          filename: github-metrics.svg
